/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaDatos.Bodegas;
import CapaDatos.Grupos;
import CapaDatos.Lineas;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import CapaNegocios.ArticulosJpaController;
import CapaNegocios.BodegasJpaController;
import CapaNegocios.GruposJpaController;
import CapaNegocios.LineasJpaController;
import CapaNegocios.clsExportarExcel;
import java.io.IOException;

import java.math.BigInteger;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author mario
 */
public class Articulos1 extends javax.swing.JFrame {

    ArticulosJpaController articulo = new ArticulosJpaController(entityMain.getInstance());
    BodegasJpaController tipob = new BodegasJpaController(entityMain.getInstance());
    GruposJpaController tipog = new GruposJpaController(entityMain.getInstance());
    LineasJpaController tipos = new LineasJpaController(entityMain.getInstance());
    boolean estado = true;
    clsExportarExcel obj;

    /**
     * Creates new form Articulos
     */
    public Articulos1() {
        initComponents();
        llenarComboBodega();
        llenarComboGrupo();
        //llenarComboLineas();
        AutoCompleteDecorator.decorate(cbbodega);
        AutoCompleteDecorator.decorate(cbgrupo);
        AutoCompleteDecorator.decorate(cbsub);
        verTabla();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtutilidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtexistenciamin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtcodbarras = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtcodpro = new javax.swing.JTextField();
        txtnomArticulos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bnguardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bneliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bneditar = new javax.swing.JButton();
        cbgrupo = new javax.swing.JComboBox<>();
        cbsub = new javax.swing.JComboBox<>();
        cbbodega = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtexistencia = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        cmbTipoArt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Grupo:");

        jLabel8.setText("Sub-Grupo:");

        jLabel9.setText("Bodega:");

        jLabel10.setText("Existencia Minima:");

        jLabel11.setText("Buscar Artículo por:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Articulos");

        jButton2.setText("Generar Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtcodpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodproActionPerformed(evt);
            }
        });

        txtnomArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomArticulosActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo de Producto");

        jLabel3.setText("Codigo de Barras:");

        bnguardar.setText("Guardar");
        bnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnguardarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre:");

        bneliminar.setText("Eliminar");
        bneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bneliminarActionPerformed(evt);
            }
        });

        jLabel6.setText("Utilidad:");

        bneditar.setText("Editar");
        bneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bneditarActionPerformed(evt);
            }
        });

        cbgrupo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbgrupoItemStateChanged(evt);
            }
        });

        jLabel19.setText("ID");

        txtId.setEnabled(false);

        jLabel12.setText("Existencia:");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        cmbTipoArt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Código Producto", "Código Barra" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(70, 70, 70)
                        .addComponent(txtexistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(63, 63, 63))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(70, 70, 70)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcodpro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcodbarras, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtexistenciamin, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtutilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbbodega, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(bnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbgrupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbsub, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbTipoArt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(232, 232, 232)))))
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(bneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(bneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtcodpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtcodbarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnomArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtexistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtexistenciamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(cmbTipoArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(bneditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbbodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtutilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodproActionPerformed

    private void txtnomArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomArticulosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomArticulosActionPerformed

    private void bnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnguardarActionPerformed
        Guardar();
    }//GEN-LAST:event_bnguardarActionPerformed

    private void bneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bneditarActionPerformed
        Editar();
    }//GEN-LAST:event_bneditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            obj = new clsExportarExcel();
            obj.exportarExcel(tabla);
        } catch (IOException ex) {
            Logger.getLogger(Articulos1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbgrupoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbgrupoItemStateChanged
        String cbLinea = this.cbgrupo.getSelectedItem().toString();
        BigDecimal idLinea;
        LineasJpaController l = new LineasJpaController(entityMain.getInstance());
        GruposJpaController grupo = new GruposJpaController(entityMain.getInstance());
        CapaDatos.Grupos g = new CapaDatos.Grupos();

        try {
            g = grupo.findIdGrupo(cbLinea);
            idLinea = g.getCodigogrupo();
            llenarComboLineas(idLinea);
            this.cbsub.setEnabled(true);
        } catch (Exception e) {
            //System.out.println("Error al llenar combo de productos." + e.toString());
            this.cbsub.setEnabled(false);
        }
    }//GEN-LAST:event_cbgrupoItemStateChanged

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        estado = true;
        LimpiarControles();
        cbbodega.setSelectedIndex(0);
        cbgrupo.setSelectedIndex(0);

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void bneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bneliminarActionPerformed
        Eliminar();
    }//GEN-LAST:event_bneliminarActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        Busqueda(this.cmbTipoArt.getSelectedItem().toString());
    }//GEN-LAST:event_txtBusquedaKeyReleased

    public void Busqueda(String columna) { //Nombre Código Producto Código Barra
        String vColumna = "";
        if (columna.equals("Nombre")) {
            vColumna = "nombrearticulo";
        }
        if (columna.equals("Código Producto")) {
            vColumna = "codigoproductos";
        }
        if (columna.equals("Código Barra")) {
            vColumna = "codigobarra";
        }

        try {
            String[] titulos = {"Código", "Nombre", "Codigo Producto", "Codigo Barras", "Existencia",
                "Existencia Min.", "Utilidad", "Bodega", "Grupo", "Sub Grupo"};

            CapaNegocios.ArticulosJpaController llenado = new CapaNegocios.ArticulosJpaController(entityMain.getInstance());
            llenado.fillJTable(this.tabla, "Articulos", vColumna, this.txtBusqueda.getText(), titulos);
            this.tabla.setDefaultEditor(Object.class, null);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error en la búsqueda. " + e.toString());
        }
    }

    public void Guardar() {
        String nombre = this.txtnomArticulos.getText();
        String codprod = this.txtcodpro.getText();
        String codbarras = this.txtcodbarras.getText();
        double utilidad = Double.parseDouble(this.txtutilidad.getText());
        int existenciamin = Integer.parseInt(this.txtexistenciamin.getText());
        int existencia = Integer.parseInt(this.txtexistencia.getText());
        int tipoProv = EncontrarBodega(this.cbbodega.getSelectedItem().toString());
        int tipoProv1 = EncontrarGrupos(this.cbgrupo.getSelectedItem().toString());
        int tipoProv2 = EncontrarLineas(this.cbsub.getSelectedItem().toString());

        Bodegas type = new Bodegas();
        Grupos gru = new Grupos();
        Lineas lin = new Lineas();
        ArticulosJpaController t = new ArticulosJpaController(entityMain.getInstance());
        CapaDatos.Articulos pro = new CapaDatos.Articulos();
        BigDecimal idNewArticulo = t.findIdNewArticulos();

        type.setCodigobodega(BigDecimal.valueOf(tipoProv));
        type.setNombrebodega(this.cbbodega.getSelectedItem().toString());

        gru.setCodigogrupo(BigDecimal.valueOf(tipoProv1));
        gru.setNombregrupo(this.cbgrupo.getSelectedItem().toString());

        lin.setCodigolinea(BigDecimal.valueOf(tipoProv2));
        lin.setNombrelineas(this.cbsub.getSelectedItem().toString());

        pro.setCodigoarticulo(idNewArticulo);
        pro.setNombrearticulo(nombre);
        pro.setCodigoproductos(codprod);
        pro.setCodigobarra(codbarras);
        pro.setExistencia(BigInteger.valueOf(existencia));
        pro.setExistenciamin(BigInteger.valueOf(existenciamin));
        pro.setUtilidad(BigDecimal.valueOf(utilidad));
        pro.setCodigogrupo(gru);
        pro.setCodigobodega(type);
        pro.setCodigolinea(lin);

        if (estado == true) {
            try {
                t.create(pro);
                llenarTabla();
                JOptionPane.showMessageDialog(null, "Artículo creado exitosamente.");
                LimpiarControles();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Hubo un error al guardar nuevo artículo. " + e.toString());
            }
        } else {
            int idP = Integer.parseInt(this.txtId.getText());
            pro.setCodigoarticulo(BigDecimal.valueOf(idP));

            try {
                t.edit(pro);
                llenarTabla();
                JOptionPane.showMessageDialog(null, "Artículo editado exitosamente.");
                LimpiarControles();
                estado = true;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Hubo un error al editar. " + e.toString());
            }
        }

    }

    private void Editar() {
        try {
            int indice = this.tabla.getSelectedRow();
            LimpiarControles();
            this.txtId.setText(tabla.getModel().getValueAt(indice, 0).toString());
            this.txtcodpro.setText(tabla.getModel().getValueAt(indice, 2).toString());
            this.txtcodbarras.setText(tabla.getModel().getValueAt(indice, 3).toString());
            this.txtnomArticulos.setText(tabla.getModel().getValueAt(indice, 1).toString());
            this.txtexistencia.setText(tabla.getModel().getValueAt(indice, 4).toString());
            this.txtexistenciamin.setText(tabla.getModel().getValueAt(indice, 5).toString());
            this.txtutilidad.setText(tabla.getModel().getValueAt(indice, 6).toString());
            this.cbbodega.setSelectedItem(tabla.getModel().getValueAt(indice, 7).toString());
            this.cbgrupo.setSelectedItem(tabla.getModel().getValueAt(indice, 8).toString());
            this.cbsub.setSelectedItem(tabla.getModel().getValueAt(indice, 9).toString());

            estado = false;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Es necesario primero seleccionar una fila para editar.");
            estado = true;
        }
    }

    private void Eliminar() {

        try {
            int indice = this.tabla.getSelectedRow();
            int codigoA = Integer.parseInt(tabla.getModel().getValueAt(indice, 0).toString());
            String articulo = tabla.getModel().getValueAt(indice, 1).toString();
            ArticulosJpaController t = new ArticulosJpaController(entityMain.getInstance());

            int r = JOptionPane.showConfirmDialog(null, "¿Desea eliminar al artículo " + articulo + "?", "Eliminar",
                    JOptionPane.YES_NO_CANCEL_OPTION);

            if (r == JOptionPane.YES_OPTION) {

                try {
                    t.destroy(BigDecimal.valueOf(codigoA));
                    verTabla();
                    llenarTabla();
                    JOptionPane.showMessageDialog(null, "Artículo eliminado con éxito.");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al eliminar." + e.toString());
                }

            } else if (r == JOptionPane.NO_OPTION) {

            } else if (r == JOptionPane.CLOSED_OPTION) {

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Es necesario primero seleccionar una fila para eliminar.");
            estado = true;
        }
    }

    private int EncontrarBodega(String prov) {
        int retorno = 0;
        BodegasJpaController t = new BodegasJpaController(entityMain.getInstance());
        CapaDatos.Bodegas pro = new CapaDatos.Bodegas();

        try {
            pro = t.findIdBodegas(prov);
            retorno = Integer.parseInt(pro.getCodigobodega().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error al encontrar el id del proveedor. " + e.toString());
        }

        return retorno;
    }

    private int EncontrarGrupos(String prov) {
        int retorno = 0;
        GruposJpaController t = new GruposJpaController(entityMain.getInstance());
        CapaDatos.Grupos pro = new CapaDatos.Grupos();

        try {
            pro = t.findIdGrupo(prov);
            retorno = Integer.parseInt(pro.getCodigogrupo().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error al encontrar el id. " + e.toString());
        }

        return retorno;
    }

    private int EncontrarLineas(String prov) {
        int retorno = 0;
        LineasJpaController t = new LineasJpaController(entityMain.getInstance());
        CapaDatos.Lineas pro = new CapaDatos.Lineas();

        try {
            pro = t.findIdLineas(prov);
            retorno = Integer.parseInt(pro.getCodigolinea().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error al encontrar el id. " + e.toString());
        }

        return retorno;
    }

    DefaultComboBoxModel dc = new DefaultComboBoxModel();

    private void llenarComboBodega() {
        cbbodega.setModel(dc);
        List<Bodegas> Listatipo;
        Listatipo = tipob.findBodegasEntities();
        for (int i = 0; i < Listatipo.size(); i++) {
            dc.addElement(Listatipo.get(i).getNombrebodega());
        }
    }
    DefaultComboBoxModel dc1 = new DefaultComboBoxModel();

    private void llenarComboGrupo() {
        cbgrupo.setModel(dc1);
        List<Grupos> Listatipo;
        Listatipo = tipog.findGruposEntities();
        for (int i = 0; i < Listatipo.size(); i++) {
            dc1.addElement(Listatipo.get(i).getNombregrupo());
        }
    }

    DefaultComboBoxModel dc2 = new DefaultComboBoxModel();

    private void llenarComboLineas(BigDecimal linea) {

        LineasJpaController l = new LineasJpaController(entityMain.getInstance());
        String val = linea.toString();
        l.fillCombo(this.cbsub, val);

    }

    public void LimpiarControles() {
        this.txtId.setText("");
        this.txtcodbarras.setText("");
        this.txtcodpro.setText("");
        this.txtexistencia.setText("");
        this.txtexistenciamin.setText("");
        this.txtnomArticulos.setText("");
        this.txtutilidad.setText("");
        this.cbbodega.setSelectedIndex(0);
        this.cbgrupo.setSelectedIndex(0);
        this.cbsub.setSelectedIndex(0);
    }

    public static DefaultTableModel tbpro;

    private void verTabla() {
        try {
            tbpro = (new DefaultTableModel(
                    null, new String[]{
                        "Código", "Nombre", "Codigo Producto", "Codigo Barras", "Existencia", "Existencia Min.",
                        "Utilidad", "Bodega", "Grupo", "Sub Grupo"}) {
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columbIndex) {
                    return types[columbIndex];
                }

                @Override
                public boolean isCellEditable(int rowIdex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            tabla.setModel(tbpro);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error");
        }
    }

    private void llenarTabla() {

        try {
            Object A[] = null;
            List<CapaDatos.Articulos> Listatipo;
            Listatipo = articulo.findArticulosEntities();
            for (int i = 0; i < Listatipo.size(); i++) {

                tbpro.addRow(A);
                tbpro.setValueAt(Listatipo.get(i).getCodigoarticulo(), i, 0);
                tbpro.setValueAt(Listatipo.get(i).getNombrearticulo(), i, 1);
                tbpro.setValueAt(Listatipo.get(i).getCodigoproductos(), i, 2);
                tbpro.setValueAt(Listatipo.get(i).getCodigobarra(), i, 3);
                tbpro.setValueAt(Listatipo.get(i).getExistencia(), i, 4);
                tbpro.setValueAt(Listatipo.get(i).getExistenciamin(), i, 5);
                tbpro.setValueAt(Listatipo.get(i).getUtilidad(), i, 6);
                tbpro.setValueAt(Listatipo.get(i).getCodigobodega().getNombrebodega(), i, 7);
                tbpro.setValueAt(Listatipo.get(i).getCodigogrupo().getNombregrupo(), i, 8);
                tbpro.setValueAt(Listatipo.get(i).getCodigolinea().getNombrelineas(), i, 9);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Articulos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Articulos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Articulos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Articulos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Articulos1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bneditar;
    private javax.swing.JButton bneliminar;
    private javax.swing.JButton bnguardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbbodega;
    private javax.swing.JComboBox<String> cbgrupo;
    private javax.swing.JComboBox<String> cbsub;
    private javax.swing.JComboBox<String> cmbTipoArt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtcodbarras;
    private javax.swing.JTextField txtcodpro;
    private javax.swing.JTextField txtexistencia;
    private javax.swing.JTextField txtexistenciamin;
    private javax.swing.JTextField txtnomArticulos;
    private javax.swing.JTextField txtutilidad;
    // End of variables declaration//GEN-END:variables
}
