/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaDatos.*;
import CapaNegocios.*;
import java.math.BigDecimal;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author mario
 */
public class Proveedores extends javax.swing.JFrame {

    ProveedoresJpaController tabla = new ProveedoresJpaController(entityMain.getInstance());
    TipoproveedoresJpaController tipoP = new TipoproveedoresJpaController(entityMain.getInstance());
    boolean estado = true; //Cuando está en true es para guardar uno nuevo. Cuando está en false es para guardar algo 
    //que se está editando.

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
        llenarComboTipo();
        AutoCompleteDecorator.decorate(comboTipoProv);
        verTabla();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtBusqueda = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtRegistro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGiro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rbEmpresa = new javax.swing.JRadioButton();
        rbPersona = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        txtNcr = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        comboTipoProv = new javax.swing.JComboBox<>();
        comboContribuyente = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtLimite = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCtaPorPagar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtTelefono = new javax.swing.JFormattedTextField();
        txtDui = new javax.swing.JFormattedTextField();
        txtNit = new javax.swing.JFormattedTextField();
        txtCelular = new javax.swing.JFormattedTextField();
        txtFecha = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla1);

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre:");

        jLabel6.setText("Telefono:");

        btnRegistrar.setText("Guardar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel7.setText("DUI:");

        jLabel8.setText("NIT:");

        jLabel9.setText("Email:");

        jLabel10.setText("Giro:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Proveedores");

        jLabel5.setText("Registro:");

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha de Ingreso:");

        jLabel3.setText("Direccion:");

        jLabel11.setText("Buscar un Proveedor:");

        buttonGroup1.add(rbEmpresa);
        rbEmpresa.setText("Empresa");

        buttonGroup1.add(rbPersona);
        rbPersona.setSelected(true);
        rbPersona.setText("Persona");

        jLabel14.setText("NCR:");

        jLabel15.setText("Saldo:");

        jLabel16.setText("Celular:");

        comboTipoProv.setEditable(true);

        comboContribuyente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grande", "Mediana", "Pequeña" }));

        jLabel17.setText("Tipo de Proveedor:");

        jLabel18.setText("Tipo de Contribuyente:");

        jLabel19.setText("ID");

        txtId.setEnabled(false);

        jLabel20.setText("Limite:");

        jLabel21.setText("Cuenta por Pagar:");

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try {
            txtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtNit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-######-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitActionPerformed(evt);
            }
        });

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(439, 439, 439)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 465, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(347, 347, 347))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbPersona)
                        .addGap(18, 18, 18)
                        .addComponent(rbEmpresa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(jLabel4)
                            .addComponent(jLabel14)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtGiro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(79, 79, 79)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel20))
                                                .addGap(28, 28, 28))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNcr, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCtaPorPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(144, 144, 144)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtDui, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNit, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboTipoProv, 0, 92, Short.MAX_VALUE)
                                            .addComponent(comboContribuyente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                            .addComponent(txtTelefono)
                                            .addComponent(txtCelular))
                                        .addGap(96, 96, 96)
                                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPersona)
                    .addComponent(jLabel2)
                    .addComponent(rbEmpresa)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtNcr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCtaPorPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel18))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboTipoProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboContribuyente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnEliminar)
                    .addComponent(jButton1))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Guardar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Editar();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LimpiarControles();
        estado = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitActionPerformed
/*
    "Codigo", "Proveedor", "NRC", "Fecha Ingreso", "Saldo", "Direccion", */
    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        String []titulos = {"Codigo","Proveedor","NRC","Fecha Ingreso","Saldo","Dirección",
        "Email", "Registro","Nit", "Dui", "Giro", "Limite", "Cuenta Por Pagar", "CodigoTipoContribuyente", 
        "Tipo Proveedor", "Telefono", "Celular"};
        
        CapaNegocios.ProveedoresJpaController llenado = new CapaNegocios.ProveedoresJpaController(entityMain.getInstance());
        llenado.fillJTable(this.tabla1, "Producto","producto",this.txtBusqueda.getText(), titulos);
        this.tabla1.setDefaultEditor(Object.class,null);
    }//GEN-LAST:event_txtBusquedaKeyTyped

    public void Guardar() {
        String fecha = this.txtFecha.getText();
        String nombre = this.txtNombre.getText();
        String direccion = this.txtDireccion.getText();
        String registro = this.txtRegistro.getText();
        String giro = this.txtGiro.getText();
        double saldo = Double.parseDouble(this.txtSaldo.getText());
        String ncr = this.txtNcr.getText();
        String dui = this.txtDui.getText();
        String nit = this.txtNit.getText();
        String limite = this.txtLimite.getText();
        String email = this.txtEmail.getText();
        String tel = this.txtTelefono.getText();
        String cel = this.txtCelular.getText();
        String ctaPorPagar = this.txtCtaPorPagar.getText();
        int tipoProv = EncontrarProveedor(this.comboTipoProv.getSelectedItem().toString());
        int tipoContr = ComprobacionComboContr();
        Tipoproveedores type = new Tipoproveedores();
        Tipocontribuyente contr = new Tipocontribuyente();
        ProveedoresJpaController t = new ProveedoresJpaController(entityMain.getInstance());
        CapaDatos.Proveedores pro = new CapaDatos.Proveedores();
        BigDecimal idNewProveedor = t.findIdNewProveedor();

        type.setCodtipoprov(BigDecimal.valueOf(tipoProv));
        type.setTipoprov(this.comboTipoProv.getSelectedItem().toString());
        contr.setCodigotipocontribuyente(BigDecimal.valueOf(tipoContr));
        contr.setTipocontribuyente(this.comboContribuyente.getSelectedItem().toString());

        pro.setCodigoproveedor(idNewProveedor);
        pro.setNombres(nombre);
        pro.setFechaingreso(fecha);
        pro.setDireccion(direccion);
        pro.setRegistro(registro);
        pro.setGiro(giro);
        pro.setSaldo(BigDecimal.valueOf(saldo));
        pro.setNrc(ncr);
        pro.setDui(dui);
        pro.setNit(nit);
        pro.setLimite(limite);
        pro.setEmail(email);
        pro.setCuentaporpagar(ctaPorPagar);
        pro.setCodigotipocontribuyente(contr);
        pro.setCodtipoprov(type);

        if (estado == true) {
            try {
                t.create(pro);
                GuardarTelefonos(pro, tel, cel, true); //para guardar telefono y celular
                llenarTabla();
                JOptionPane.showMessageDialog(null, "Proveedor creado exitosamente.");
                LimpiarControles();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Hubo un error al guardar nuevo proveedor. " + e.toString());
            }
        } else {
            int idP = Integer.parseInt(this.txtId.getText());
            pro.setCodigoproveedor(BigDecimal.valueOf(idP));

            try {
                t.edit(pro);
                GuardarTelefonos(pro, tel, cel, false);
                llenarTabla();
                JOptionPane.showMessageDialog(null, "Proveedor editado exitosamente.");
                LimpiarControles();
                estado = true;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Hubo un error al editar. " + e.toString());
            }
        }

    }

    private void GuardarTelefonos(CapaDatos.Proveedores p, String telefono, String cel, boolean var) {
        TelefonosproveedorJpaController t = new TelefonosproveedorJpaController(entityMain.getInstance());
        
        if (var == true) {
            
            CapaDatos.Telefonosproveedor nuevoT = new CapaDatos.Telefonosproveedor();
            CapaDatos.Telefonosproveedor nuevoC = new CapaDatos.Telefonosproveedor();

            nuevoT.setCodigoproveedor(p);
            nuevoT.setTelefono(telefono);
            nuevoT.setTipo("T");

            nuevoC.setCodigoproveedor(p);
            nuevoC.setTelefono(cel);
            nuevoC.setTipo("C");
            
            try {
                t.create(nuevoT);
                t.create(nuevoC);
                System.out.println("Telefono y Celular creado con éxito.");
                
            } catch (Exception e) {
                System.out.println("Hubo un error. " + e.toString());
            }
            
        } else {
            try {
                t.editTelProveedor(Integer.parseInt(p.getCodigoproveedor().toString()), telefono, cel);
                System.out.println("Telefono y Celular editado con éxito.");
                
            } catch (Exception e) {
                System.out.println("Hubo un error. " + e.toString());
            }
        }
    }

    private void Eliminar() {

        try {
            int indice = this.tabla1.getSelectedRow();
            int codigoP = Integer.parseInt(tabla1.getModel().getValueAt(indice, 0).toString());
            String proveedor = tabla1.getModel().getValueAt(indice, 1).toString();
            ProveedoresJpaController t = new ProveedoresJpaController(entityMain.getInstance());
            TelefonosproveedorJpaController telPro = new TelefonosproveedorJpaController(entityMain.getInstance());

            int r = JOptionPane.showConfirmDialog(null, "¿Desea eliminar a " + proveedor + "?", "Acción de Eliminar",
                    JOptionPane.YES_NO_CANCEL_OPTION);

            if (r == JOptionPane.YES_OPTION) {
                //Primero eliminamos los telefonos
                int idTelefono = telPro.findIdTel(codigoP, "T");
                int idCel = telPro.findIdTel(codigoP, "C");
                
                try {
                    telPro.destroy(BigDecimal.valueOf(idTelefono));
                    telPro.destroy(BigDecimal.valueOf(idCel));
                } catch (Exception e){
                    
                }
                //Luego eliminamos el proveedor
                try {
                    t.destroy(BigDecimal.valueOf(codigoP));
                    verTabla();
                    llenarTabla();
                    JOptionPane.showMessageDialog(null, "Proveedor eliminado con éxito.");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al eliminar." + e.toString());
                }

            } else if (r == JOptionPane.NO_OPTION) {

            } else if (r == JOptionPane.CLOSED_OPTION) {

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Es necesario primero seleccionar una fila para eliminar.");
            estado = true;
        }
    }

    private void Editar() {
        try {
            int indice = this.tabla1.getSelectedRow();
            LimpiarControles();
            this.txtId.setText(tabla1.getModel().getValueAt(indice, 0).toString());
            this.txtNombre.setText(tabla1.getModel().getValueAt(indice, 1).toString());
            this.txtNcr.setText(tabla1.getModel().getValueAt(indice, 2).toString());
            this.txtFecha.setText(tabla1.getModel().getValueAt(indice, 3).toString());
            this.txtSaldo.setText(tabla1.getModel().getValueAt(indice, 4).toString());
            this.txtDireccion.setText(tabla1.getModel().getValueAt(indice, 5).toString());
            this.txtEmail.setText(tabla1.getModel().getValueAt(indice, 6).toString());
            this.txtRegistro.setText(tabla1.getModel().getValueAt(indice, 7).toString());
            this.txtNit.setText(tabla1.getModel().getValueAt(indice, 8).toString());
            this.txtDui.setText(tabla1.getModel().getValueAt(indice, 9).toString());
            this.txtGiro.setText(tabla1.getModel().getValueAt(indice, 10).toString());
            this.txtLimite.setText(tabla1.getModel().getValueAt(indice, 11).toString());
            this.txtCtaPorPagar.setText(tabla1.getModel().getValueAt(indice, 12).toString());
            this.comboContribuyente.setSelectedItem(tabla1.getModel().getValueAt(indice, 13).toString());
            this.comboTipoProv.setSelectedItem(tabla1.getModel().getValueAt(indice, 14).toString());
            this.txtTelefono.setText(tabla1.getModel().getValueAt(indice, 15).toString());
            this.txtCelular.setText(tabla1.getModel().getValueAt(indice, 16).toString());

            estado = false;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Es necesario primero seleccionar una fila para editar.");
            estado = true;
        }
    }

    private int EncontrarProveedor(String prov) {
        int retorno = 0;
        TipoproveedoresJpaController t = new TipoproveedoresJpaController(entityMain.getInstance());
        CapaDatos.Tipoproveedores pro = new CapaDatos.Tipoproveedores();

        try {
            pro = t.findIdTipoproveedores(prov);
            retorno = Integer.parseInt(pro.getCodtipoprov().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error al encontrar el id del proveedor. " + e.toString());
        }

        return retorno;
    }

    private int ComprobacionComboContr() {
        int retorno = this.comboContribuyente.getSelectedIndex();
        return retorno + 1;
    }

    DefaultComboBoxModel dc = new DefaultComboBoxModel();

    private void llenarComboTipo() {
        comboTipoProv.setModel(dc);
        List<Tipoproveedores> Listatipo;
        Listatipo = tipoP.findTipoproveedoresEntities();
        for (int i = 0; i < Listatipo.size(); i++) {
            dc.addElement(Listatipo.get(i).getTipoprov());
        }
    }

    public void LimpiarControles() {
        this.txtId.setText("");
        this.txtCelular.setText("");
        this.txtCtaPorPagar.setText("");
        this.txtDireccion.setText("");
        this.txtDui.setText("");
        this.txtEmail.setText("");
        this.txtFecha.setText("");
        this.txtGiro.setText("");
        this.txtLimite.setText("");
        this.txtNcr.setText("");
        this.txtNit.setText("");
        this.txtNombre.setText("");
        this.txtRegistro.setText("");
        this.txtSaldo.setText("");
        this.txtTelefono.setText("");
        this.comboContribuyente.setSelectedIndex(0);
        this.comboTipoProv.setSelectedIndex(0);
    }

    public static DefaultTableModel tbpro;

    private void verTabla() {
        try {
            tbpro = (new DefaultTableModel(
                    null, new String[]{
                        "Codigo", "Proveedor", "NRC", "Fecha Ingreso", "Saldo", "Direccion", "Email", "Registro",
                        "Nit", "Dui", "Giro", "Limite", "Cuenta Por Pagar", "CodigoTipoContribuyente", "Tipo Proveedor",
                        "Telefono", "Celular"}) {
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columbIndex) {
                    return types[columbIndex];
                }

                @Override
                public boolean isCellEditable(int rowIdex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            tabla1.setModel(tbpro);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error");
        }
    }
//"Nit", "Dui", "Giro", "Limite", "Cuenta Por Pagar", "CodigoTipoContribuyente", "Tipo Proveedor"

    private void llenarTabla() {
        int valorId = 0;
        String tipo;
        TelefonosproveedorJpaController t = new TelefonosproveedorJpaController(entityMain.getInstance());

        try {
            Object A[] = null;
            List<CapaDatos.Proveedores> Listatipo;
            Listatipo = tabla.findProveedoresEntities();
            for (int i = 0; i < Listatipo.size(); i++) {
                valorId = Integer.parseInt(Listatipo.get(i).getCodigoproveedor().toString());

                tbpro.addRow(A);
                tbpro.setValueAt(Listatipo.get(i).getCodigoproveedor(), i, 0);
                tbpro.setValueAt(Listatipo.get(i).getNombres(), i, 1);
                tbpro.setValueAt(Listatipo.get(i).getNrc(), i, 2);
                tbpro.setValueAt(Listatipo.get(i).getFechaingreso(), i, 3);
                tbpro.setValueAt(Listatipo.get(i).getSaldo(), i, 4);
                tbpro.setValueAt(Listatipo.get(i).getDireccion(), i, 5);
                tbpro.setValueAt(Listatipo.get(i).getEmail(), i, 6);
                tbpro.setValueAt(Listatipo.get(i).getRegistro(), i, 7);
                tbpro.setValueAt(Listatipo.get(i).getNit(), i, 8);
                tbpro.setValueAt(Listatipo.get(i).getDui(), i, 9);
                tbpro.setValueAt(Listatipo.get(i).getGiro(), i, 10);
                tbpro.setValueAt(Listatipo.get(i).getLimite(), i, 11);
                tbpro.setValueAt(Listatipo.get(i).getCuentaporpagar(), i, 12);
                tbpro.setValueAt(Listatipo.get(i).getCodigotipocontribuyente().getTipocontribuyente(), i, 13);
                tbpro.setValueAt(Listatipo.get(i).getCodtipoprov().getTipoprov(), i, 14);
                tbpro.setValueAt(t.findTelProveedor(valorId, "T"), i, 15);
                tbpro.setValueAt(t.findTelProveedor(valorId, "C"), i, 16);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboContribuyente;
    private javax.swing.JComboBox<String> comboTipoProv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbEmpresa;
    private javax.swing.JRadioButton rbPersona;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtCtaPorPagar;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JFormattedTextField txtDui;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtGiro;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLimite;
    private javax.swing.JTextField txtNcr;
    private javax.swing.JFormattedTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRegistro;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JFormattedTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
